# Generated by Django 2.2.2 on 2019-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='summary',
            field=models.TextField(default='', max_length=200),
        ),
    ]
