# Generated by Django 2.2.2 on 2019-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20190626_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_details',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
