# Generated by Django 2.2.2 on 2019-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projects_image_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='video',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
