# Generated by Django 2.2.2 on 2019-06-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_projects_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
