# Generated by Django 2.2.2 on 2019-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_video',
            field=models.CharField(default='', max_length=200),
        ),
    ]
