# Generated by Django 2.2.2 on 2019-06-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20190627_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title_video',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
