# Generated by Django 2.2.2 on 2019-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='image',
            field=models.ImageField(default='ptf_v2/static/No_image_3x4.svg.png', upload_to='images/'),
        ),
    ]
