# Generated by Django 2.2.2 on 2019-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='image',
            field=models.ImageField(default='ptf_v2/static/No_image_3x4.svg.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
