# Generated by Django 2.2.2 on 2019-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0002_auto_20190627_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
