# Generated by Django 2.2.2 on 2019-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0003_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='image',
            field=models.ImageField(default='static/No_image_3x4.png', upload_to='images/'),
        ),
    ]
